config/routes.rb
Rails.application.routes.draw do

  #Specifiying the routes for the application needed right now
  get '/' => redirect { |params| 'http://localhost:3000/stations/1' }
  root to: 'stations#index'

  resources :vehicles, only: [:index]
  resources :stations, only: [:show]

  resources :locations, only: [:new, :create]

  get '/:any_other_url'=> redirect { |params| 'http://localhost:3000/stations/1' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord

  belongs_to :vehicle
  delegate :station, :to => :vehicle, :allow_nil => true

  # Here calculating other values like distance, angle and direction
  # All calculation are done by using Geocoder
  def set_defaults

    response = "AllOK"
    location_coordinates = [self.latitude, self.longitude]

    station = self.vehicle.station
    station_coordinates = [station.latitude, station.longitude]

    last_location = Location.where(vehicle_id: self.vehicle_id).order(id: :desc).first

    # To check either new location exceeding from the boundry or not
    self.distance = (Geocoder::Calculations.distance_between(station_coordinates,location_coordinates, options = {units: :km})).to_f
    unless self.distance <= station.radius
      response = "ExceedCityBoundaries"
    end

    # Specific check for the last location either available or not
    # If available then angle calculated from last location
    # Otherwise from the station location
    if last_location.nil?
      angle = Geocoder::Calculations.bearing_between(station_coordinates, location_coordinates)
      self.angle = angle.to_s
      self.direction = (Geocoder::Calculations.compass_point(angle, points = %w[N NE E SE S SW W NW])).to_s
    else
      last_location_coordinates = [last_location.latitude, last_location.longitude]
      if (last_location.recorded_at + 3.seconds) < (self.recorded_at)
        angle = Geocoder::Calculations.bearing_between(last_location_coordinates, location_coordinates)
        self.angle = angle.to_s
        self.direction = (Geocoder::Calculations.compass_point(angle, points = %w[N NE E SE S SW W NW])).to_s
      else
        response = "LessThan3Seconds"
      end
    end
    response

  end

end

app/models/station.rb
class Station < ApplicationRecord

  #Creating relations with other models
  has_many :vehicles
  has_many :locations, through: :vehicles

  accepts_nested_attributes_for :vehicles

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

  #Creating relations with other models
  belongs_to :station
  has_many :locations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  #CMD
  # rails g scaffold station latitude:float longitude:float name:string radius:float
  # rails g scaffold vehicle route:string uid:string station:references
  # rails g scaffold location latitude:float longitude:float recorded_at:datetime angle:string vehicle:references
  # rails g channel vehicle
  #

  require 'singleton'

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  def new
    @location = Location.new
  end

  def create
    #Creating new location and calculating values and then responded back to action cable
    @location = Location.new(location_params)
    response = @location.set_defaults
    puts response
    if response == "AllOK"
      if @location.save
        location_html = ApplicationController.render(
          partial: 'locations/location',
          locals: { location: @location, vehicle: @location.vehicle }
        )
      else
        response = "RecordNotSave"
      end
    end
    #calling action cable for specific vehicle
    ActionCable.server.broadcast "vehicle_channel_#{@location.vehicle_id}", response: response, location: @location, location_html: location_html

  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:latitude, :longitude, :recorded_at, :angle, :vehicle_id, :distance, :direction)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  include Singleton
  before_action :set_station, only: %i[ show ]

  def index
    link_to 'Show', Station.first
  end

  def show
    #Getting the needed values for stations show function
    @vehicles = @station.vehicles
    @vehicle = @vehicles.find_by(id: params[:vehicle_id]) unless params[:vehicle_id].blank?
    @locations = @vehicle.try(:locations)
    render 'index'
  end

  private
    def set_station
      #Setting station function
      unless params[:id].blank?
        @station = Station.find(params[:id])
      else
        @station = Station.find(1)
      end
    end

    def set_vehicle
      #Setting Vehicle function
      unless params[:vehicle_id].blank?
        @vehicle = Vehicle.find(params[:vehicle_id])
      else
        @vehicle = Vehicle.find(1)
      end
    end

    def station_params
      params.require(:station).permit(:latitude, :longitude, :name, :radius)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  def index
    @vehicles = Vehicle.all
  end

  def show
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save
    redirect_to request.referer
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:route, :uid, :station_id, :destination, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-dark navbar-static-down navbar-expand-md">
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav mr-auto right">
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top">
  <div class="custom-nav">
    <div class="container">
      <%= link_to "Allygator Shuttle", root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav navbar-right">
<!--          <li class='nav-item'><%#= link_to '', root_path, method: :delete, class: 'nav-link' %></li>-->
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Allygator Shuttle" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "About Allygator Shuttle" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>

  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Add Fresh Latitude" %>
    <%= form.text_field :latitude, class: 'form-control', placeholder: "Latitude of Vehicle" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label "Add Fresh Longitude" %>
    <%= form.text_field :longitude, class: 'form-control', placeholder: "Longitude of Vehicle" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label "Add Recorded Time" %>
    <br>
    <%= form.datetime_select :recorded_at, class: 'form-control', placeholder: "Recorded time of location" %>
  </div>

  <%= form.hidden_field :vehicle_id, value: vehicle.id %>

  <br>
  <%#= form.submit "Add ", class: "btn btn-outline-primary btn-block" %>
  <div class="input-group-append">
    <%= form.submit "Add Fresh Location", class: "btn btn-outline-primary btn-block" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="location mb-2">
      <div class="content-container">
        <div class="description">
          <h1><%= location.id %>. Vehicle - <%= vehicle.uid + " ( From: " + vehicle.route + " - To: " + vehicle.try(:destination) + " )" %> </h1>
          <h2>
            Recorded at : <%= location.recorded_at? ? location.recorded_at.strftime("%a, %B %d, %I:%M:%S %p") : "No Recorded date"%>
          </h2>
          <p> </p>
          <div class="content">
            <%= location.latitude %> ,
            <%= location.longitude %>
          </div>
          <div class="content">
            <p2><%= location.direction %></p2>
            , Angle :
            <%= location.angle %>
          </div>
          <div class="content">
            Distance :
            <%= location.distance %>
          </div>

        </div>


        <div class="author">

        </div>

        <div class="author">

        </div>
      </div>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/stations/_form.html.erb
<%= form_with(model: station) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
        <% station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lattitude %>
    <%= form.text_field :lattitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :radius %>
    <%= form.text_field :radius %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/index.html.erb
<div id="vehicle-id" data-vehicle-id="<%= @vehicle.try(:id) %>"></div>

<div class="container-fluid">
  <hr>
    <div class="row">
      <div class="col-4">
        <h1> Add New Vehicle</h1>
        <%= render 'vehicles/form', vehicle: Vehicle.new, station: Station.first %>
      </div>
      <div class="col-4">
        <h1> Vehicle List </h1>
        <div class="vehicles-list">
          <% if @vehicles.present? and @station.present? %>
            <% @vehicles.each do |vehicle| %>
              <%= link_to station_path(vehicle_id: vehicle)  do %>
                <div class="card mb-2">
                  <div class="card-body">
                    <%=  vehicle.id.to_s + "- " + vehicle.uid + " ( From: " + vehicle.route + " - To: " + vehicle.try(:destination) + " )" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <% if @vehicle.present? %>
          <div id="vehicle-id" data-vehicle-id="<%= @vehicle.try(:id) %>"></div>
          <h1> New Location <%= @vehicle.uid %></h1>
          <h4> From: <%= @vehicle.route %> - To: <%= @vehicle.destination %></h4>
          <div class="chat-box">
            <%= render 'locations/form', location: Location.new, vehicle: @vehicle, station: @station %>
          </div>
        <% else %>
          <h1> Please Select Any Vehicle </h1>
          <br>
          <h3> List of Vehicle in the Right Box or create a new one...!!</h3>
          <br>
          <h5> This will open connection for specific vehicle with socket and then you can add locations for this chosen vehicle</h5>
        <% end %>
      </div>
    </div>
  <hr>
</div>
</div>

<div class="error" id="response">
  <hr>
</div>

<br>

<div class="container-fluid">

  <div id="containerIntro">
    <h1>Locations </h1>
    <p3 id="location-count"><%= @locations.present? ? @locations.count : 0 %></p3>
  </div>

  <div class="locations-list" id="locations">
    <div id="list">
      <% if @locations.present? %>
          <% @locations.each do |location| %>
            <%= render 'locations/location', location: location, vehicle: @vehicle %>
          <% end %>
      <% end %>
    </div>
  </div>

</div>

<hr>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Vehicle Uid" %>
    <%= form.text_field :uid, class: 'form-control', placeholder: "Vehicle UID (like M65)" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label "Enter Route" %>
    <%= form.text_field :route, class: 'form-control', placeholder: "Vehicle Starting Place" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label "Enter Destination" %>
    <%= form.text_field :destination, class: 'form-control', placeholder: "Vehicle Destination Place" %>
  </div>

  <%= form.hidden_field :station_id, value: station.id %>

  <%= form.submit "Add Vehicle in the pool", class: "btn btn-outline-primary btn-block" %>
<% end %>

<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>